version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=graphql
      - MYSQL_USER=graphql
      - MYSQL_DATABASE=graphql
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1